#!/bin/sh

# This file runs when a DM logs you into a graphical session.
# If you use startx/xinit like a Chad, this file will also be sourced.

#for optimus-manager
sleep 2
/usr/bin/prime-offload

#Dual monitor setup
#xrandr --output eDP1 --primary --mode 1920x1080 --output HDMI1 --mode 1366x768 --right-of eDP1
xrandr --output eDP-1-1 --primary --mode 1920x1080 --output HDMI-1-1 --mode 1366x768 --right-of eDP-1-1

# Music daemon
#mpd &			# music player daemon-you might prefer it as a service though

# GTK application delay fix
# dbus-update-activation-environment --systemd DBUS_SESSION_BUS_ADDRESS DISPLAY XAUTHORITY


dwmblocks &

remaps &		# run the remaps script, switching caps/esc and more; check it for more info
setbg &			# set the background with the `setbg` script

xrdb ${XDG_CONFIG_HOME:-$HOME/.config}/x11/xresources &	# Uncomment to use Xresources colors/settings on startup

# Compositors
xcompmgr &		# xcompmgr for transparency
# picom --experimental-backend &


dunst &			# dunst for notifications
xset r rate 300 50 &	# Speed xrate up
unclutter &		# Remove mouse when idle
xset -dpms &
sxhkd & #hotkey daemon
TouchpadToggle &
#keepassxc &
clipmenud &
transmission-daemon &
# sudo qbittorrent-nox -d --webui-port=6060 &
#xinput set-prop 10 "libinput Accel Speed" -0.8


# This line autostarts an instance of Pulseaudio that does not exit on idle.
# This is "necessary" on Artix due to a current bug between PA and
# Chromium-based browsers where they fail to start PA and use dummy output.
pidof -s runit &&
	! pidof -s pulseaudio >/dev/null 2>&1 &&
	setsid -f pulseaudio --start --exit-idle-time=-1 >/dev/null 2>&1
